# Generated by Django 2.2.6 on 2019-10-24 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vp_app', '0002_question_date_concluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='vp_app.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vp_app.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='vp_app.Answer')),
            ],
        ),
        migrations.RenameField(
            model_name='record',
            old_name='total_responses',
            new_name='total_replies',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
