# Generated by Django 2.2.6 on 2019-10-24 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp_app', '0003_auto_20191023_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
