# Generated by Django 2.2.6 on 2019-11-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vp_app', '0004_delete_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'replies'},
        ),
    ]
